[2025-04-18T20:55:03.812+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-18T20:50:00+00:00 [queued]>
[2025-04-18T20:55:03.819+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-18T20:50:00+00:00 [queued]>
[2025-04-18T20:55:03.821+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-18T20:55:03.830+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-18 20:50:00+00:00
[2025-04-18T20:55:03.838+0000] {standard_task_runner.py:60} INFO - Started process 5468 to run task
[2025-04-18T20:55:03.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_ingestion_dag', 'load_to_snowflake', 'scheduled__2025-04-18T20:50:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/mbta_ingestion_dag.py', '--cfg-path', '/tmp/tmp9gkdvp8w']
[2025-04-18T20:55:03.848+0000] {standard_task_runner.py:88} INFO - Job 180: Subtask load_to_snowflake
[2025-04-18T20:55:03.885+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-18T20:50:00+00:00 [running]> on host 4144a051706e
[2025-04-18T20:55:03.935+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T20:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T20:50:00+00:00'
[2025-04-18T20:55:03.937+0000] {mbta_ingestion_dag.py:35} INFO - üöÄ Launching Kafka consumer to process and load data into Snowflake...
[2025-04-18T20:55:03.937+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-18T20:55:03.939+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-18T20:55:07.953+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0xffff68c39760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /session/v1/login-request?request_id=a7937141-ef4c-47ef-8e78-ef6ac4801468&databaseName=MBTA_DB2&schemaName=MBTA_SCHEMA2&warehouse=MBTA_WH2&request_guid=107f717f-d7ae-4b20-8d4c-5a98b02ccca7
[2025-04-18T20:55:17.009+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0xffff68c06790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /session/v1/login-request?request_id=2ab37495-534f-425c-ad94-479d1ad4d1ac&databaseName=MBTA_DB2&schemaName=MBTA_SCHEMA2&warehouse=MBTA_WH2&request_guid=8872bc2a-4457-4b5c-8424-4036f41d3070
[2025-04-18T20:55:21.031+0000] {mbta_kafka_consumer.py:48} ERROR - ‚ùå Error connecting to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
[2025-04-18T20:55:21.059+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-18T20:55:21.079+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
