[2025-04-23T00:49:28.138+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:25:00+00:00 [queued]>
[2025-04-23T00:49:28.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:25:00+00:00 [queued]>
[2025-04-23T00:49:28.262+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 2
[2025-04-23T00:49:28.425+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-04-23 00:25:00+00:00
[2025-04-23T00:49:28.476+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2025-04-23T00:49:28.485+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_kafka_consumer_dag', 'run_kafka_consumer', 'scheduled__2025-04-23T00:25:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/mbta_kafka_consumer_dag.py', '--cfg-path', '/tmp/tmpqsjhjgyo']
[2025-04-23T00:49:28.513+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask run_kafka_consumer
[2025-04-23T00:49:28.970+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:25:00+00:00 [running]> on host c76075383b29
[2025-04-23T00:49:29.443+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_kafka_consumer_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:25:00+00:00'
[2025-04-23T00:49:29.456+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T00:49:29.459+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T00:49:30.289+0000] {mbta_kafka_consumer.py:45} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T00:49:30.290+0000] {mbta_kafka_consumer.py:219} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T00:49:30.314+0000] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-04-23T00:49:30.314+0000] {conn.py:322} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
[2025-04-23T00:49:30.315+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-04-23T00:49:30.316+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.03 secs
[2025-04-23T00:49:30.365+0000] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-04-23T00:49:30.368+0000] {conn.py:322} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
[2025-04-23T00:49:30.369+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-04-23T00:49:30.371+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.08 secs
[2025-04-23T00:49:30.472+0000] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-04-23T00:49:30.473+0000] {conn.py:322} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
[2025-04-23T00:49:30.475+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-04-23T00:49:30.476+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.15 secs
[2025-04-23T00:49:30.631+0000] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-04-23T00:49:30.632+0000] {conn.py:322} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
[2025-04-23T00:49:30.635+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-04-23T00:49:30.636+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.32 secs
